language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
env:
  matrix:
    - ZENCODER_PY_JSON_MODULE=simplejson

install:
  - pip install simplejson
  - pip install -e .
# command to run tests
script: nosetests

